packages:
  - crates/forge-job
  - crates/forge-server
  - packages/forge-components
autoInstallPeers: false
verifyDepsBeforeRun: false
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  lefthook: true
  protobufjs: true
