[package]
name = "forge-job"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "frontend-forge-job"
path = "src/main.rs"

[dependencies]
flate2.workspace = true
forge-core = { path = "../../crates/forge-core" }
forge-project-generator = { path = "../../crates/forge-project-generator" }
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
tar.workspace = true
tempfile.workspace = true

